package com.airpick.airpick_service.models;

public enum NotificationType {
    WELCOME,
    MATCH_CREATED,
    MATCH_ACCEPTED,
    MATCH_REJECTED,
    MATCH_CANCELLED,
    MATCH_IN_PROGRESS,
    MATCH_DELIVERED,
    NEW_PROPOSAL,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    PROPOSAL_WITHDRAWN,
    OFFER_FULLY_MATCHED,
    OFFER_CANCELLED,
    OFFER_REQUEST_CANCELLED,
    NEW_MESSAGE
}
